#! /bin/sh


sxhkd &
compton &
xset r rate 150 30
export PATH=$HOME/scripts:$PATH

if [ $(xrandr --query| grep ' connected' -o | wc -l) -gt 1 ]; then
	xrandr --output eDP-1 --off
fi

$HOME/.config/polybar/launch.sh &
$HOME/.fehbg &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0
#bspc monitor HDMI-1 -d 1 2 3 4 5
#bspc monitor DP-1 -d 6 7 8 9 0

bspc config border_width         3
bspc config window_gap		 0

bspc config normal_border_color  \#282c34
bspc config focused_border_color \#61AFEF

bspc config split_ratio           0.52
bspc config borderless_monocle    true
bspc config gapless_monocle       true
bspc config focus_follows_pointer false
#bspc config initial_polarity     first_child
bspc config initial_polarity     second_child

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Gpick state=floating follow=on
bspc rule -a Chromium desktop='^10'
bspc rule -a Firefox desktop='^10'
bspc rule -a Opera desktop='^10'
bspc rule -a Zathura state=tiled
bspc rule -a Transmission-gtk desktop='^9' follow=on
